### Importing the database

In [1]:
%load_ext sql
%sql sqlite:////Users/Shobhit/Downloads/traffic.db

## 1. How many total pageviews and pageviews per day?

### Total pageviews

In [2]:
%%sql

select count(*) as total_pageviews 
from events
where event = 'pageview';

 * sqlite:////Users/Shobhit/Downloads/traffic.db
Done.

[(142015,)]

### Pageviews for each date

In [3]:
%%sql

select date, count(event) as pageviews
from events
where event = 'pageview'
group by date;

 * sqlite:////Users/Shobhit/Downloads/traffic.db
Done.

[('2021-08-19', 22366),
 ('2021-08-20', 21382),
 ('2021-08-21', 21349),
 ('2021-08-22', 20430),
 ('2021-08-23', 18646),
 ('2021-08-24', 18693),
 ('2021-08-25', 19149)]

## 2. Other events

### What different types of events do we have?

In [4]:
%%sql

select event
from events
group by event;

 * sqlite:////Users/Shobhit/Downloads/traffic.db
Done.

[('click',), ('pageview',), ('preview',)]

### Total clicks and per day clicks

In [5]:
%%sql

select count(*) as total_clicks
from events
where event = 'click';

 * sqlite:////Users/Shobhit/Downloads/traffic.db
Done.

[(55732,)]

In [6]:
%%sql

select date, count(event) as clicks
from events
where event = 'click'
group by date;

 * sqlite:////Users/Shobhit/Downloads/traffic.db
Done.

[('2021-08-19', 9207),
 ('2021-08-20', 8508),
 ('2021-08-21', 8071),
 ('2021-08-22', 7854),
 ('2021-08-23', 7315),
 ('2021-08-24', 7301),
 ('2021-08-25', 7476)]

### Total previews and per day previews

In [7]:
%%sql

select count(*) as total_previews
from events
where event = 'preview';

 * sqlite:////Users/Shobhit/Downloads/traffic.db
Done.

[(28531,)]

In [8]:
%%sql

select date, count(event) as previews
from events
where event = 'preview'
group by date;

 * sqlite:////Users/Shobhit/Downloads/traffic.db
Done.

[('2021-08-19', 3788),
 ('2021-08-20', 4222),
 ('2021-08-21', 4663),
 ('2021-08-22', 4349),
 ('2021-08-23', 3847),
 ('2021-08-24', 3840),
 ('2021-08-25', 3822)]

## 3. Which countries the pageviews come from?

In [9]:
%%sql

select distinct(country)
from events
where event = 'pageview';

 * sqlite:////Users/Shobhit/Downloads/traffic.db
Done.

[('Saudi Arabia',),
 ('United States',),
 ('Ireland',),
 ('United Kingdom',),
 ('France',),
 ('Guatemala',),
 ('Jordan',),
 ('Kuwait',),
 ('Pakistan',),
 ('Italy',),
 ('Germany',),
 ('Iraq',),
 ('Peru',),
 ('India',),
 ('Nicaragua',),
 ('Rwanda',),
 ('Tanzania',),
 ('United Arab Emirates',),
 ('Norway',),
 ('Oman',),
 ('Bahamas',),
 ('Algeria',),
 ('Czechia',),
 ('Mexico',),
 ('Jamaica',),
 ('Netherlands',),
 ('Colombia',),
 ('Morocco',),
 ('Australia',),
 ('Myanmar',),
 ('Uzbekistan',),
 ('Austria',),
 ('Latvia',),
 ('Turkey',),
 ('Mauritania',),
 ('Sri Lanka',),
 ('Bosnia and Herzegovina',),
 ('Estonia',),
 ('Nigeria',),
 ('Bulgaria',),
 ('Greece',),
 ('El Salvador',),
 ('Philippines',),
 ('Denmark',),
 ('Serbia',),
 ('Canada',),
 ('Spain',),
 ('Libya',),
 ('Palestine',),
 ('Chad',),
 ('Ecuador',),
 ('Mali',),
 ('Romania',),
 ('Switzerland',),
 ('Portugal',),
 ('Slovenia',),
 ('Iceland',),
 ('Sweden',),
 ('Bahrain',),
 ('Egypt',),
 ('Lithuania',),
 ('Liberia',),
 ('Israel',),
 ('Ukraine',),
 ('Puerto Rico',),
 ('South Africa',),
 ('Ghana',),
 ('Kenya',),
 ('Armenia',),
 ('Nepal',),
 ('Barbados',),
 ('Azerbaijan',),
 ('Qatar',),
 ('Uganda',),
 ('Poland',),
 ('Brazil',),
 ('Guyana',),
 ('Fiji',),
 ('Bangladesh',),
 ('Belgium',),
 ('Hong Kong',),
 ('Haiti',),
 ('Botswana',),
 ('Ivory Coast',),
 ('Bhutan',),
 ('Indonesia',),
 ('Réunion',),
 ('Cameroon',),
 ('Singapore',),
 ('Yemen',),
 ('French Guiana',),
 ('Slovakia',),
 ('Dominican Republic',),
 ('Russia',),
 ('Cabo Verde',),
 ('Kyrgyzstan',),
 ('New Zealand',),
 ('U.S. Virgin Islands',),
 ('Albania',),
 ('Venezuela',),
 ('Burkina Faso',),
 ('Montenegro',),
 ('Paraguay',),
 ('Bolivia',),
 ('Cyprus',),
 ('Mayotte',),
 ('Thailand',),
 ('Maldives',),
 ('Tunisia',),
 ('Namibia',),
 ('Costa Rica',),
 ('Croatia',),
 ('Trinidad and Tobago',),
 ('Senegal',),
 ('Suriname',),
 ('Malaysia',),
 ('Honduras',),
 ('DR Congo',),
 ('South Korea',),
 ('Finland',),
 ('Mozambique',),
 ('Hungary',),
 ('Kazakhstan',),
 ('Zambia',),
 ('Somalia',),
 ('Moldova',),
 ('Cayman Islands',),
 ('Saint Vincent and the Grenadines',),
 ('Martinique',),
 ('Guadeloupe',),
 ('Kosovo',),
 ('Sudan',),
 ('Saint Lucia',),
 ('Uruguay',),
 (None,),
 ('Mauritius',),
 ('Aruba',),
 ('Curaçao',),
 ('British Virgin Islands',),
 ('Vietnam',),
 ('Laos',),
 ('Sierra Leone',),
 ('Seychelles',),
 ('Guinea',),
 ('Lebanon',),
 ('Angola',),
 ('Belize',),
 ('Togo',),
 ('Turks and Caicos Islands',),
 ('Georgia',),
 ('Gabon',),
 ('Argentina',),
 ('North Macedonia',),
 ('Benin',),
 ('Ethiopia',),
 ('Niger',),
 ('Zimbabwe',),
 ('St Kitts and Nevis',),
 ('Malawi',),
 ('Chile',),
 ('Madagascar',),
 ('Panama',),
 ('Luxembourg',),
 ('Grenada',),
 ('Greenland',),
 ('Mongolia',),
 ('Taiwan',),
 ('Liechtenstein',),
 ('Anguilla',),
 ('Principality of Monaco',),
 ('Djibouti',),
 ('Samoa',),
 ('Åland',),
 ('Eswatini',),
 ('Faroe Islands',),
 ('Cambodia',),
 ('China',),
 ('French Polynesia',),
 ('Papua New Guinea',),
 ('Japan',),
 ('Lesotho',),
 ('Eritrea',),
 ('Iran',),
 ('Antigua and Barbuda',),
 ('Burundi',),
 ('Belarus',),
 ('Guinea-Bissau',),
 ('Bermuda',),
 ('Gambia',),
 ('Isle of Man',),
 ('American Samoa',),
 ('Tajikistan',),
 ('Comoros',),
 ('Jersey',),
 ('Andorra',),
 ('Brunei',),
 ('Congo Republic',),
 ('Syria',),
 ('Dominica',),
 ('New Caledonia',),
 ('Marshall Islands',),
 ('Macao',),
 ('Gibraltar',),
 ('Palau',),
 ('Solomon Islands',),
 ('Malta',),
 ('Wallis and Futuna',),
 ('Afghanistan',),
 ('Central African Republic',),
 ('Guernsey',),
 ('Sint Maarten',),
 ('Saint Martin',)]

## 4.Overall click rate

### Count total clicks

In [10]:
%%sql

select count(*) 
from events 
where event = 'click';

 * sqlite:////Users/Shobhit/Downloads/traffic.db
Done.

[(55732,)]

### Count total pageviews

In [11]:
%%sql

select count(*) 
from events 
where event = 'pageview';

 * sqlite:////Users/Shobhit/Downloads/traffic.db
Done.

[(142015,)]

### Click rate (clicks/pageviews)

In [12]:
%%sql

select
(select cast(count(*) as float) 
from events
where event = 'click')
/
(select cast(count(*) as float)
from events 
where event = 'pageview');

 * sqlite:////Users/Shobhit/Downloads/traffic.db
Done.

[(0.3924374185825441,)]